### ISSUE TITLE
Camparative case on real numbers in function of the number of fundamental memories

### ISSUE THREAD

**Issue by Fideliszan** [fitolobo/Learning-Rules-to-Hopfield-Type-Associative-Memories#1]
Sobre o experimento em que variamos o número de memórias fundamentais..... No último gráfico das comparações do caso real (p=60) vc usou N=100? Ou N=200? Em todos você usou N=200. Nesse último caso está escrito que você usou N=100.

**Comment by fitolobo** [comment]
Em todos utilizei 200, você me fala.do caption da imagem no overleaf? É
provável que tenha esquecido mudar.

**Comment by Fideliszan** [comment]
Beleza. Sem problemas.

Em sex, 6 de nov de 2020 22:38, fitolobo <notifications@github.com>
escreveu:

> Em todos utilizei 200, você me fala.do caption da imagem no overleaf? É
> provável que tenha esquecido mudar.
>
> El vie., 6 de nov. de 2020 23:28, Fidelis Zanetti de Castro <
